spring:
  application:
    name: orders-spring-kafka
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    schema: public
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: ${spring.datasource.schema}
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: orders-group
      auto-offset-reset: earliest
  jackson:
    default-property-inclusion: NON_EMPTY
    time-zone: UTC
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false